### PR TITLE
Add Queen Elizabeth II's Death to banned topics list

### PR DESCRIPTION
**Pull request by Southpaw1496**

### CODE REVIEW

**Comment by gdude2002** [comment]
Your indent is wrong and will prevent the file from being parsed.

**Comment by gdude2002** [comment]
Nope. What are you editing with?

**Comment by Southpaw1496** [comment]
GitHub's web interface

**Comment by gdude2002** [comment]
Use spaces to match the indentation of the text on the lines above. Additionally, you need an extra newline before the line you added, just like the rest of that block.

**Comment by gdude2002** [comment]
Thanks, that looks good

**Pull request merged**
