### PR TITLE
(Incomplete) Add Github <-> Discord team syncing

### PR DESCRIPTION
**Pull request by TheGlitch76**
Not nearly done and still has a lot of noise. Basic features will include linking a Discord user and a Github one (currently not verified, not sure if there's a need + sounds like a PITA), linking a discord role with a Github team, and allowing certain discord roles to add/remove members of that team.

I'm currently attempting to implement a minimal prototype. Once I have the basic features, UX and other necessities (does the role make you a `@Quilt Developer`?, etc) will come later.

Opening this PR in case I work too slowly for someone else. 
I will clean up the git history before this PR is ready for review.

### CODE REVIEW

**Comment by TheGlitch76** [comment]
This needs formatting and merging work but is otherwise Good Enough:tm: for a first go-around--only thing that needs added still is the quilt developer role

**Comment by gdude2002** [comment]
I'm guessing this _really_ needs revisiting at this point, given it was opened in December of last year and hasn't had a push in five months. The existing code has managed to hold up well, though!

**Comment by gdude2002** [comment]
Now that Cozy has admin perms on GitHub, this can probably be revisited.

**Comment by gdude2002** [comment]
A year of downtime is impressive!

**Comment by gdude2002** [comment]
This has long been inactive, so I'm closing it for now.

I think this is going to need a rework given our GH teams have been reorganised and we don't have a toolchain server to deal with anymore, either way.

**Pull request closed without merging**
