### PR TITLE
Mod hosting link/loader flag verification

### PR DESCRIPTION
**Pull request by SilverAndro**
Implements a module that checks links posted in "release" channels (channels that have mod releases posted to them) and makes sure that they're marked as quilt compatible

Fast exits on any project being marked as quilt compatible, otherwise will re-queue for up to 3 days (Curseforge takes weekend breaks for project approval) and if it still doesnt exist it stops without flagging anything, this isnt saved across restarts right now if that would be wanted.

Projects are placed in a global queue if they fail in order to generate *much* cleaner logs, although I could reverse that decision if wanted.

Contacting the user follows a few fallback steps of:
- Attempt to DM the user
- Attempt to send a message in a thread attached to the original message
- Create a thread on the message and send there

Still somewhat WIP, needs logging and some other cleanup

### CODE REVIEW

**Comment by gdude2002** [comment]
What's the status of this? It's been a couple months since any commits were made.

**Comment by SilverAndro** [comment]
Been caught up with college unfortunately

It currently mainly just needs like, logging and maybe some cleanup I believe?

All the functionality works though, I don't think any (major at least) changes need to be made?

**Comment by gdude2002** [comment]
This isn't a branch on this repo so it'd be difficult for me to make those changes for you - any idea on when you might be able to finish it up?

**Comment by SilverAndro** [comment]
I can probably tackle it soon? By the weekend I should have some time at least to get something reviewable

**Comment by SilverAndro** [comment]
Ok added some more logging, I think everything should be good for review? Ill move it out of draft

**Review by gdude2002 — APPROVED** [review]
Finally getting around to this - great work, let's ship it!

**Comment by gdude2002** [comment]
Looks like we've got a build failure. It's a small one, though.

image

**Comment by gdude2002** [comment]
Cheers!

**Pull request merged**
