### PR TITLE
Update to KordEx v2

### PR DESCRIPTION
**Pull request by gdude2002**
This PR makes the following changes:

- Update to KordEx v2
- Remove `@WiredPlugin` usage and replace it with the `plugin { }` block in the Gradle plugin configuration
- Remove the mappings extension, since @sschr15 is still AWOL and hasn't OK'd it for KordEx v2's licensing
- Configure the new `/about` command
- Set the data collection mode to "Minimal" (decided by @OroArmor)
- Fix the formatting in the Minecraft patch notes extension b/c it was pissing me off (format blockquotes and italics, triple embed length)
  - This also includes an "update" command that requests that a message be edited with the patch notes of the given version
  - I also fixed the permissions for the `/mc` management subcommands, as previously they required both the mod role _and_ the admin perm, when they should've accepted _either_

You should use the `dev` Gradle task to launch the bot in development going forward, instead of `run`

For more information on what changed in v2, [make sure you read up!](https://docs.kordex.dev/about#version-2)

As usual, I don't have an environment to test this in. It was a pretty painless update, but someone should still test it before merging.

# BEFORE YOU MERGE CHECKLIST

- [x] Test the bot
  - [x] Update your IDE config to use the `dev` Gradle task instead of `run` for testing

### CODE REVIEW

**Review by OroArmor — APPROVED** [review]

**Comment by kb-1000** [comment]
Removing the mappings feature does make cozy quite a bit less useful IMO

**Comment by gdude2002** [comment]
That change was also made at the request of the infra team, who are currently working with limited machine resources.

**Comment by gdude2002** [comment]
Please note that we've run into a problem with how KSP generates its tasks - it seems to be a timing issue created by KSP, and I'm still looking for a way to work around it in the KordEx plugin.

**Comment by gdude2002** [comment]
This problem has been fixed.

**Comment by gdude2002** [comment]
I fixed the patch notes. Merry Chrysler.

**Review by Southpaw1496 — APPROVED** [review]
I've tested the bot and it seems to be working as intended. A couple of notes:
- You've already made the necessary IDE updates for IDEA users, right?
- I've noticed that there's a lot of line breaks in between headings with the `mc` command. Is this new behaviour?
Screenshot 2024-10-04 at 6 00 44 pm

**Comment by gdude2002** [comment]
> You've already made the necessary IDE updates for IDEA users, right?

I'm an IDEA user and things seem to work fine?

> I've noticed that there's a lot of line breaks in between headings

There are no additional line breaks iirc, it's just that it uses actual markdown headings now - feel free to remove one of them if you think it'd work better

**Pull request merged**
